[package]
name = "common-testing"
version = "1.0.0"
edition.workspace = true
authors = ["Kerber0x <kerber0x@protonmail.com>"]
description = "Common types and utils for testing"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://whitewhale.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
cosmwasm-schema.workspace = true
cw-multi-test.workspace = true
amm.workspace = true
epoch-manager.workspace = true
osmosis-std.workspace = true
