blank_issues_enabled: true
contact_links:
  - name: I want help using MANTRA DEX's contracts.
    url: https://discord.com/channels/1143334664757588050/1143339661050269758
    about: Ask your questions about how to use a particular piece of our infrastructure in your dapp or bots.
