[package]
name = "mantra-utils"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
cosmwasm-std.workspace = true
cw-ownable.workspace = true
